# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'not_hesaplama.ui',
# licensing of 'not_hesaplama.ui' applies.
#
# Created: Wed Aug  8 23:34:07 2018
#      by: pyside2-uic  running on PySide2 5.11.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(727, 689)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.egitim_yili_cbox = QtWidgets.QComboBox(self.centralwidget)
        self.egitim_yili_cbox.setObjectName("egitim_yili_cbox")
        self.gridLayout_2.addWidget(self.egitim_yili_cbox, 0, 3, 1, 1)
        self.kod_sec_cbox = QtWidgets.QComboBox(self.centralwidget)
        self.kod_sec_cbox.setMinimumSize(QtCore.QSize(70, 0))
        self.kod_sec_cbox.setObjectName("kod_sec_cbox")
        self.kod_sec_cbox.addItem("")
        self.gridLayout_2.addWidget(self.kod_sec_cbox, 0, 1, 1, 1)
        self.egitim_yili_label = QtWidgets.QLabel(self.centralwidget)
        self.egitim_yili_label.setObjectName("egitim_yili_label")
        self.gridLayout_2.addWidget(self.egitim_yili_label, 0, 2, 1, 1)
        self.kod_sec_label = QtWidgets.QLabel(self.centralwidget)
        self.kod_sec_label.setObjectName("kod_sec_label")
        self.gridLayout_2.addWidget(self.kod_sec_label, 0, 0, 1, 1)
        self.egitim_donemi_cbox = QtWidgets.QComboBox(self.centralwidget)
        self.egitim_donemi_cbox.setObjectName("egitim_donemi_cbox")
        self.gridLayout_2.addWidget(self.egitim_donemi_cbox, 1, 3, 1, 1)
        self.egitim_donemi_label = QtWidgets.QLabel(self.centralwidget)
        self.egitim_donemi_label.setObjectName("egitim_donemi_label")
        self.gridLayout_2.addWidget(self.egitim_donemi_label, 1, 2, 1, 1)
        self.season_select = QtWidgets.QPushButton(self.centralwidget)
        self.season_select.setObjectName("season_select")
        self.gridLayout_2.addWidget(self.season_select, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lesson_table = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lesson_table.sizePolicy().hasHeightForWidth())
        self.lesson_table.setSizePolicy(sizePolicy)
        self.lesson_table.setMinimumSize(QtCore.QSize(0, 0))
        self.lesson_table.setRowCount(0)
        self.lesson_table.setColumnCount(5)
        self.lesson_table.setObjectName("lesson_table")
        self.lesson_table.setColumnCount(5)
        self.lesson_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.lesson_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lesson_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lesson_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.lesson_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.lesson_table.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_2.addWidget(self.lesson_table)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gen_not_ort_label = QtWidgets.QLabel(self.centralwidget)
        self.gen_not_ort_label.setMinimumSize(QtCore.QSize(0, 0))
        self.gen_not_ort_label.setMaximumSize(QtCore.QSize(134567, 16777215))
        self.gen_not_ort_label.setObjectName("gen_not_ort_label")
        self.gridLayout.addWidget(self.gen_not_ort_label, 2, 3, 1, 1)
        self.don_not_ort_label = QtWidgets.QLabel(self.centralwidget)
        self.don_not_ort_label.setObjectName("don_not_ort_label")
        self.gridLayout.addWidget(self.don_not_ort_label, 3, 3, 1, 1)
        self.ders_kodu_cbox = QtWidgets.QComboBox(self.centralwidget)
        self.ders_kodu_cbox.setMinimumSize(QtCore.QSize(70, 0))
        self.ders_kodu_cbox.setObjectName("ders_kodu_cbox")
        self.ders_kodu_cbox.addItem("")
        self.gridLayout.addWidget(self.ders_kodu_cbox, 1, 1, 1, 1)
        self.don_not_ort_gos = QtWidgets.QLabel(self.centralwidget)
        self.don_not_ort_gos.setText("")
        self.don_not_ort_gos.setObjectName("don_not_ort_gos")
        self.gridLayout.addWidget(self.don_not_ort_gos, 3, 4, 1, 1)
        self.not_cbox = QtWidgets.QComboBox(self.centralwidget)
        self.not_cbox.setObjectName("not_cbox")
        self.not_cbox.addItem("")
        self.gridLayout.addWidget(self.not_cbox, 3, 1, 1, 1)
        self.not_label = QtWidgets.QLabel(self.centralwidget)
        self.not_label.setObjectName("not_label")
        self.gridLayout.addWidget(self.not_label, 3, 0, 1, 1)
        self.ders_kodu_label = QtWidgets.QLabel(self.centralwidget)
        self.ders_kodu_label.setMaximumSize(QtCore.QSize(110, 16777215))
        self.ders_kodu_label.setObjectName("ders_kodu_label")
        self.gridLayout.addWidget(self.ders_kodu_label, 1, 0, 1, 1)
        self.ders_no_label = QtWidgets.QLabel(self.centralwidget)
        self.ders_no_label.setObjectName("ders_no_label")
        self.gridLayout.addWidget(self.ders_no_label, 2, 0, 1, 1)
        self.ders_no_cbox = QtWidgets.QComboBox(self.centralwidget)
        self.ders_no_cbox.setObjectName("ders_no_cbox")
        self.ders_no_cbox.addItem("")
        self.gridLayout.addWidget(self.ders_no_cbox, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.ders_cikar = QtWidgets.QPushButton(self.centralwidget)
        self.ders_cikar.setObjectName("ders_cikar")
        self.gridLayout.addWidget(self.ders_cikar, 1, 4, 1, 1)
        self.gen_not_ort_gos = QtWidgets.QLabel(self.centralwidget)
        self.gen_not_ort_gos.setText("")
        self.gen_not_ort_gos.setObjectName("gen_not_ort_gos")
        self.gridLayout.addWidget(self.gen_not_ort_gos, 2, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setObjectName("add")
        self.verticalLayout.addWidget(self.add)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 727, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.kod_sec_cbox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Seç", None, -1))
        self.egitim_yili_label.setText(QtWidgets.QApplication.translate("MainWindow", "Eğitim Yılını Seç", None, -1))
        self.kod_sec_label.setText(QtWidgets.QApplication.translate("MainWindow", "Bölüm Kodunu Seç", None, -1))
        self.egitim_donemi_label.setText(QtWidgets.QApplication.translate("MainWindow", "Eğitim Dönemini Seç", None, -1))
        self.season_select.setText(QtWidgets.QApplication.translate("MainWindow", "SEÇ", None, -1))
        self.lesson_table.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Ders Kodu", None, -1))
        self.lesson_table.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Ders İsmi", None, -1))
        self.lesson_table.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Kredi", None, -1))
        self.lesson_table.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Not", None, -1))
        self.lesson_table.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Durum", None, -1))
        self.gen_not_ort_label.setText(QtWidgets.QApplication.translate("MainWindow", "Genel Not Ortalaması :", None, -1))
        self.don_not_ort_label.setText(QtWidgets.QApplication.translate("MainWindow", "Dönem Not Ortalaması :", None, -1))
        self.ders_kodu_cbox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Seç", None, -1))
        self.not_cbox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Seç", None, -1))
        self.not_label.setText(QtWidgets.QApplication.translate("MainWindow", "Not", None, -1))
        self.ders_kodu_label.setText(QtWidgets.QApplication.translate("MainWindow", "Ders Kodu", None, -1))
        self.ders_no_label.setText(QtWidgets.QApplication.translate("MainWindow", "Ders Numarası", None, -1))
        self.ders_no_cbox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Seç", None, -1))
        self.ders_cikar.setText(QtWidgets.QApplication.translate("MainWindow", "Seçilen Dersi Çıkar", None, -1))
        self.add.setText(QtWidgets.QApplication.translate("MainWindow", "Ders Ekle", None, -1))

